AllCops:
  Exclude:
    - Gemfile
    - Guardfile
    - Rakefile
    - bin/*
    - spec/*
    - vendor/**/*
  TargetRubyVersion: 2.7.3
  NewCops: enable

Metrics/AbcSize:
  Max: 35
Metrics/ClassLength:
  Max: 200
Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 60
Metrics/ModuleLength:
  Max: 200
