AllCops:
  Exclude:
    - Gemfile
    - Guardfile
    - Rakefile
    - bin/*
    - spec/*
    - vendor/**/*
  TargetRubyVersion: 3.1.3
  NewCops: enable


Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Max: 120
Metrics:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
